### ISSUE TITLE
error when saving an orchestration flow

### ISSUE THREAD

**Issue by jakejh** [DevDataPlatform/webapp#292]
![Image](https://github.com/DevDataPlatform/DDP_backend/assets/2295314/e3298ca9-d873-4416-a108-399a54078f48)

I specified all the info, then clicked "save changes", then this happened. I still see the error on the orchestrate page when I log out and log back in.

**Comment by fatchat** [comment]
@jakejh see if it works now?

**Comment by jakejh** [comment]
Seems ok now. Thanks for fixing.

1. There's a weird thing now, though, where the title still seems to be "daily" but the name (uneditable) is "agency-fund-airbyte-dbt-deployment". The same thing happened when I created a new flow.
1. Are all these times UTC or my local time? Where is that set?
1. Did you say that a last run status of "running" actually means "succeeded"?
1. Why can I not edit most of the settings of the flow?

**Comment by fatchat** [comment]
1. this is a name-vs-display-name bug, i've opened https://github.com/DevDataPlatform/webapp/issues/304
2. local time, we convert from utc in your browser to show it to you
3. yes ... we should change that
4. you can edit the schedule, but you can't edit the steps which comprise the flow (i.e the sync and transform pieces) because if you did then it would be a new flow

and there was another reason we chose to do it this way... editing the steps was technically challenging but i don't remember the details. we can revisit this next month if you think it would be useful to have, until then just delete-and-recreate

**Comment by jakejh** [comment]
2. What happens if I log in from a different time zone? Does the displayed time of an existing flow change? What about if I create a new flow? This could get confusing if not labeled or editable, because I believe the surveycto connector uses UTC (although it doesn't explicitly say so).
4. I think delete-and-recreate is fine, I noticed a similar thing with the connections.

**Comment by fatchat** [comment]
2. The time is consistently shown in the browser's local timezone and stored as UTC in our database. We could maybe have a little UI toggle to switch between UTC and local time #308
